### ISSUE TITLE
Timeout when click on icon. 1.8 - 1.12

### ISSUE THREAD

**Issue by king-glitch** [TrMenu/TrMenu#259]
**Describe the bug**
On 1.8 - 1.2 when click on icon it kick and saids timeout.

**To Reproduce**
1. click on icon
2. can't anything
3. kick out of the server because of `timeout`

**Expected behavior**
normal behavior as 1.13 - 1.16

**Screenshots**
https://pastebin.com/pwFHHGp8

**Additional context**
https://hasteb.in/yopowiri

**Server Information**
> Use command `/trmenu dump` to get the information
> Copy the information to below
e.g.
```
https://hasteb.in/yopowiri
```

**Comment by Arasple** [comment]
`Caused by: java.lang.NoSuchMethodError: me.clip.placeholderapi.PlaceholderAPIPlugin.getUptime()Ljava/lang/String; 

at 
`

**Comment by king-glitch** [comment]
Sometime it doesn't show anything then it just kicked when click any button on gui.

**Comment by king-glitch** [comment]
![Uploading Screen Shot 2563-12-12 at 18.12.29.png…]()

**Comment by Tanguygab** [comment]
do /papi ecloud download Server
/papi reload
and make suee you are using the latest version of PlaceholderAPI

**Comment by king-glitch** [comment]
This happened to me from version 2.0.1 until now.

I've tried to downloaded everything on Example menu.

I've tried to delete and redownload PlaceholderAPI, Trmenu and TabooLib (both folder and files).

I've tried on version 1.8, 1.12, 1.15, 1.16
on version 1.8 and 1.12 doesn't work, but on 1.15, 1.16 work perfectly.

<img width="698" alt="Screen Shot 2563-12-12 at 18 26 22" src="https://user-images.githubusercontent.com/58404132/101982574-8bf18b80-3ca7-11eb-94f3-a178afdc039d.png">

**Comment by Arasple** [comment]
It does not work on 1.8/1.12 because the placeholder you used does not compatible
I am guessing it is `%server_uptime%`, and you are using the latest expansion, which does not work well with older Minecraft version

**Comment by king-glitch** [comment]
https://pastebin.com/0DVJ3R8W

I tried to remove every placeholders.
this still happen.

```More Explanation```

when I click on any button (includes glass [no functions]) the gui stoped I my charlector freeze. I can't break any blocks, type any command, or chat. then after a while (about 30 seconds) I got disconnect with `Connection Lost` `timed out` .

**Comment by Tanguygab** [comment]
can you do /ver and send a screenshot?

**Comment by king-glitch** [comment]
on 1.8
<img width="1033" alt="Screen Shot 2563-12-12 at 18 53 19" src="https://user-images.githubusercontent.com/58404132/101983113-50f15700-3cab-11eb-8db9-064bead6de6a.png">

on 1.12.2
<img width="935" alt="Screen Shot 2563-12-12 at 18 53 55" src="https://user-images.githubusercontent.com/58404132/101983121-649cbd80-3cab-11eb-91d0-4385fb2bddb4.png">

**Comment by Tanguygab** [comment]
and the bug happens on both servers?

**Comment by king-glitch** [comment]
yes. since ver 2

**Comment by Tanguygab** [comment]
can you try with only TrMenu and PlaceholderAPI on those servers to see if it works?

**Comment by king-glitch** [comment]
Yes, It works. So I've tried to put back all of the plugins. I find out that when I only remove ProtocalLib. It works normally.

**Comment by Tanguygab** [comment]
what's your ProtocolLib version? also, canyou send your ProtocolLib config?

**Comment by king-glitch** [comment]
4.6.0-SNAPSHOT-b478


[ProtocolLib.zip](https://github.com/TrMenu/TrMenu/files/5683042/ProtocolLib.zip)

**Comment by Tanguygab** [comment]
I can't open the file

**Comment by king-glitch** [comment]
[ProtocolLib.zip](https://github.com/TrMenu/TrMenu/files/5683140/ProtocolLib.zip)

**Comment by Tanguygab** [comment]
can you send your TrMenu config?

**Comment by king-glitch** [comment]
https://pastebin.com/e5Puas8M

**Comment by Tanguygab** [comment]
can you try to disable `InventoryClickEvent: true` ? (line 84)

**Comment by king-glitch** [comment]
yes, still happen.
